{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 93,
   "id": "c41c5de5-8909-40ad-a5af-d2bcca2eb36b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: numpy in c:\\anaconda\\lib\\site-packages (1.26.4)\n",
      "Requirement already satisfied: scikit-learn in c:\\anaconda\\lib\\site-packages (1.4.2)\n",
      "Requirement already satisfied: numpy>=1.19.5 in c:\\anaconda\\lib\\site-packages (from scikit-learn) (1.26.4)\n",
      "Requirement already satisfied: scipy>=1.6.0 in c:\\anaconda\\lib\\site-packages (from scikit-learn) (1.13.1)\n",
      "Requirement already satisfied: joblib>=1.2.0 in c:\\anaconda\\lib\\site-packages (from scikit-learn) (1.4.2)\n",
      "Requirement already satisfied: threadpoolctl>=2.0.0 in c:\\anaconda\\lib\\site-packages (from scikit-learn) (2.2.0)\n",
      "Requirement already satisfied: pandas in c:\\anaconda\\lib\\site-packages (2.2.2)\n",
      "Requirement already satisfied: numpy>=1.26.0 in c:\\anaconda\\lib\\site-packages (from pandas) (1.26.4)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in c:\\anaconda\\lib\\site-packages (from pandas) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2020.1 in c:\\anaconda\\lib\\site-packages (from pandas) (2024.1)\n",
      "Requirement already satisfied: tzdata>=2022.7 in c:\\anaconda\\lib\\site-packages (from pandas) (2024.1)\n",
      "Requirement already satisfied: six>=1.5 in c:\\anaconda\\lib\\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)\n",
      "Requirement already satisfied: torch in c:\\anaconda\\lib\\site-packages (2.4.0)\n",
      "Requirement already satisfied: filelock in c:\\anaconda\\lib\\site-packages (from torch) (3.15.4)\n",
      "Requirement already satisfied: typing-extensions>=4.8.0 in c:\\anaconda\\lib\\site-packages (from torch) (4.12.2)\n",
      "Requirement already satisfied: sympy in c:\\anaconda\\lib\\site-packages (from torch) (1.12)\n",
      "Requirement already satisfied: networkx in c:\\anaconda\\lib\\site-packages (from torch) (3.2.1)\n",
      "Requirement already satisfied: jinja2 in c:\\anaconda\\lib\\site-packages (from torch) (3.1.4)\n",
      "Requirement already satisfied: fsspec in c:\\anaconda\\lib\\site-packages (from torch) (2024.6.1)\n",
      "Requirement already satisfied: setuptools in c:\\anaconda\\lib\\site-packages (from torch) (69.5.1)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in c:\\anaconda\\lib\\site-packages (from jinja2->torch) (2.1.3)\n",
      "Requirement already satisfied: mpmath>=0.19 in c:\\anaconda\\lib\\site-packages (from sympy->torch) (1.3.0)\n",
      "Requirement already satisfied: matplotlib in c:\\anaconda\\lib\\site-packages (3.8.4)\n",
      "Requirement already satisfied: contourpy>=1.0.1 in c:\\anaconda\\lib\\site-packages (from matplotlib) (1.2.0)\n",
      "Requirement already satisfied: cycler>=0.10 in c:\\anaconda\\lib\\site-packages (from matplotlib) (0.11.0)\n",
      "Requirement already satisfied: fonttools>=4.22.0 in c:\\anaconda\\lib\\site-packages (from matplotlib) (4.51.0)\n",
      "Requirement already satisfied: kiwisolver>=1.3.1 in c:\\anaconda\\lib\\site-packages (from matplotlib) (1.4.4)\n",
      "Requirement already satisfied: numpy>=1.21 in c:\\anaconda\\lib\\site-packages (from matplotlib) (1.26.4)\n",
      "Requirement already satisfied: packaging>=20.0 in c:\\anaconda\\lib\\site-packages (from matplotlib) (24.1)\n",
      "Requirement already satisfied: pillow>=8 in c:\\anaconda\\lib\\site-packages (from matplotlib) (10.3.0)\n",
      "Requirement already satisfied: pyparsing>=2.3.1 in c:\\anaconda\\lib\\site-packages (from matplotlib) (3.0.9)\n",
      "Requirement already satisfied: python-dateutil>=2.7 in c:\\anaconda\\lib\\site-packages (from matplotlib) (2.9.0.post0)\n",
      "Requirement already satisfied: six>=1.5 in c:\\anaconda\\lib\\site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)\n",
      "Requirement already satisfied: scikit-learn in c:\\anaconda\\lib\\site-packages (1.4.2)\n",
      "Requirement already satisfied: gensim in c:\\anaconda\\lib\\site-packages (4.3.2)\n",
      "Requirement already satisfied: transformers in c:\\anaconda\\lib\\site-packages (4.44.0)\n",
      "Requirement already satisfied: sentence-transformers in c:\\anaconda\\lib\\site-packages (3.0.1)\n",
      "Requirement already satisfied: numpy>=1.19.5 in c:\\anaconda\\lib\\site-packages (from scikit-learn) (1.26.4)\n",
      "Requirement already satisfied: scipy>=1.6.0 in c:\\anaconda\\lib\\site-packages (from scikit-learn) (1.13.1)\n",
      "Requirement already satisfied: joblib>=1.2.0 in c:\\anaconda\\lib\\site-packages (from scikit-learn) (1.4.2)\n",
      "Requirement already satisfied: threadpoolctl>=2.0.0 in c:\\anaconda\\lib\\site-packages (from scikit-learn) (2.2.0)\n",
      "Requirement already satisfied: smart-open>=1.8.1 in c:\\anaconda\\lib\\site-packages (from gensim) (5.2.1)\n",
      "Requirement already satisfied: filelock in c:\\anaconda\\lib\\site-packages (from transformers) (3.15.4)\n",
      "Requirement already satisfied: huggingface-hub<1.0,>=0.23.2 in c:\\anaconda\\lib\\site-packages (from transformers) (0.24.5)\n",
      "Requirement already satisfied: packaging>=20.0 in c:\\anaconda\\lib\\site-packages (from transformers) (24.1)\n",
      "Requirement already satisfied: pyyaml>=5.1 in c:\\anaconda\\lib\\site-packages (from transformers) (6.0.2)\n",
      "Requirement already satisfied: regex!=2019.12.17 in c:\\anaconda\\lib\\site-packages (from transformers) (2023.10.3)\n",
      "Requirement already satisfied: requests in c:\\anaconda\\lib\\site-packages (from transformers) (2.32.3)\n",
      "Requirement already satisfied: safetensors>=0.4.1 in c:\\anaconda\\lib\\site-packages (from transformers) (0.4.4)\n",
      "Requirement already satisfied: tokenizers<0.20,>=0.19 in c:\\anaconda\\lib\\site-packages (from transformers) (0.19.1)\n",
      "Requirement already satisfied: tqdm>=4.27 in c:\\anaconda\\lib\\site-packages (from transformers) (4.66.5)\n",
      "Requirement already satisfied: torch>=1.11.0 in c:\\anaconda\\lib\\site-packages (from sentence-transformers) (2.4.0)\n",
      "Requirement already satisfied: Pillow in c:\\anaconda\\lib\\site-packages (from sentence-transformers) (10.3.0)\n",
      "Requirement already satisfied: fsspec>=2023.5.0 in c:\\anaconda\\lib\\site-packages (from huggingface-hub<1.0,>=0.23.2->transformers) (2024.6.1)\n",
      "Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\\anaconda\\lib\\site-packages (from huggingface-hub<1.0,>=0.23.2->transformers) (4.12.2)\n",
      "Requirement already satisfied: sympy in c:\\anaconda\\lib\\site-packages (from torch>=1.11.0->sentence-transformers) (1.12)\n",
      "Requirement already satisfied: networkx in c:\\anaconda\\lib\\site-packages (from torch>=1.11.0->sentence-transformers) (3.2.1)\n",
      "Requirement already satisfied: jinja2 in c:\\anaconda\\lib\\site-packages (from torch>=1.11.0->sentence-transformers) (3.1.4)\n",
      "Requirement already satisfied: setuptools in c:\\anaconda\\lib\\site-packages (from torch>=1.11.0->sentence-transformers) (69.5.1)\n",
      "Requirement already satisfied: colorama in c:\\anaconda\\lib\\site-packages (from tqdm>=4.27->transformers) (0.4.6)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in c:\\anaconda\\lib\\site-packages (from requests->transformers) (3.3.2)\n",
      "Requirement already satisfied: idna<4,>=2.5 in c:\\anaconda\\lib\\site-packages (from requests->transformers) (3.7)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in c:\\anaconda\\lib\\site-packages (from requests->transformers) (2.2.2)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in c:\\anaconda\\lib\\site-packages (from requests->transformers) (2024.7.4)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in c:\\anaconda\\lib\\site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (2.1.3)\n",
      "Requirement already satisfied: mpmath>=0.19 in c:\\anaconda\\lib\\site-packages (from sympy->torch>=1.11.0->sentence-transformers) (1.3.0)\n",
      "Requirement already satisfied: transformers in c:\\anaconda\\lib\\site-packages (4.44.0)\n",
      "Requirement already satisfied: torch in c:\\anaconda\\lib\\site-packages (2.4.0)\n",
      "Requirement already satisfied: scikit-learn in c:\\anaconda\\lib\\site-packages (1.4.2)\n",
      "Requirement already satisfied: filelock in c:\\anaconda\\lib\\site-packages (from transformers) (3.15.4)\n",
      "Requirement already satisfied: huggingface-hub<1.0,>=0.23.2 in c:\\anaconda\\lib\\site-packages (from transformers) (0.24.5)\n",
      "Requirement already satisfied: numpy>=1.17 in c:\\anaconda\\lib\\site-packages (from transformers) (1.26.4)\n",
      "Requirement already satisfied: packaging>=20.0 in c:\\anaconda\\lib\\site-packages (from transformers) (24.1)\n",
      "Requirement already satisfied: pyyaml>=5.1 in c:\\anaconda\\lib\\site-packages (from transformers) (6.0.2)\n",
      "Requirement already satisfied: regex!=2019.12.17 in c:\\anaconda\\lib\\site-packages (from transformers) (2023.10.3)\n",
      "Requirement already satisfied: requests in c:\\anaconda\\lib\\site-packages (from transformers) (2.32.3)\n",
      "Requirement already satisfied: safetensors>=0.4.1 in c:\\anaconda\\lib\\site-packages (from transformers) (0.4.4)\n",
      "Requirement already satisfied: tokenizers<0.20,>=0.19 in c:\\anaconda\\lib\\site-packages (from transformers) (0.19.1)\n",
      "Requirement already satisfied: tqdm>=4.27 in c:\\anaconda\\lib\\site-packages (from transformers) (4.66.5)\n",
      "Requirement already satisfied: typing-extensions>=4.8.0 in c:\\anaconda\\lib\\site-packages (from torch) (4.12.2)\n",
      "Requirement already satisfied: sympy in c:\\anaconda\\lib\\site-packages (from torch) (1.12)\n",
      "Requirement already satisfied: networkx in c:\\anaconda\\lib\\site-packages (from torch) (3.2.1)\n",
      "Requirement already satisfied: jinja2 in c:\\anaconda\\lib\\site-packages (from torch) (3.1.4)\n",
      "Requirement already satisfied: fsspec in c:\\anaconda\\lib\\site-packages (from torch) (2024.6.1)\n",
      "Requirement already satisfied: setuptools in c:\\anaconda\\lib\\site-packages (from torch) (69.5.1)\n",
      "Requirement already satisfied: scipy>=1.6.0 in c:\\anaconda\\lib\\site-packages (from scikit-learn) (1.13.1)\n",
      "Requirement already satisfied: joblib>=1.2.0 in c:\\anaconda\\lib\\site-packages (from scikit-learn) (1.4.2)\n",
      "Requirement already satisfied: threadpoolctl>=2.0.0 in c:\\anaconda\\lib\\site-packages (from scikit-learn) (2.2.0)\n",
      "Requirement already satisfied: colorama in c:\\anaconda\\lib\\site-packages (from tqdm>=4.27->transformers) (0.4.6)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in c:\\anaconda\\lib\\site-packages (from jinja2->torch) (2.1.3)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in c:\\anaconda\\lib\\site-packages (from requests->transformers) (3.3.2)\n",
      "Requirement already satisfied: idna<4,>=2.5 in c:\\anaconda\\lib\\site-packages (from requests->transformers) (3.7)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in c:\\anaconda\\lib\\site-packages (from requests->transformers) (2.2.2)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in c:\\anaconda\\lib\\site-packages (from requests->transformers) (2024.7.4)\n",
      "Requirement already satisfied: mpmath>=0.19 in c:\\anaconda\\lib\\site-packages (from sympy->torch) (1.3.0)\n",
      "Requirement already satisfied: datasets in c:\\anaconda\\lib\\site-packages (2.21.0)\n",
      "Requirement already satisfied: filelock in c:\\anaconda\\lib\\site-packages (from datasets) (3.15.4)\n",
      "Requirement already satisfied: numpy>=1.17 in c:\\anaconda\\lib\\site-packages (from datasets) (1.26.4)\n",
      "Requirement already satisfied: pyarrow>=15.0.0 in c:\\anaconda\\lib\\site-packages (from datasets) (17.0.0)\n",
      "Requirement already satisfied: dill<0.3.9,>=0.3.0 in c:\\anaconda\\lib\\site-packages (from datasets) (0.3.8)\n",
      "Requirement already satisfied: pandas in c:\\anaconda\\lib\\site-packages (from datasets) (2.2.2)\n",
      "Requirement already satisfied: requests>=2.32.2 in c:\\anaconda\\lib\\site-packages (from datasets) (2.32.3)\n",
      "Requirement already satisfied: tqdm>=4.66.3 in c:\\anaconda\\lib\\site-packages (from datasets) (4.66.5)\n",
      "Requirement already satisfied: xxhash in c:\\anaconda\\lib\\site-packages (from datasets) (3.5.0)\n",
      "Requirement already satisfied: multiprocess in c:\\anaconda\\lib\\site-packages (from datasets) (0.70.16)\n",
      "Requirement already satisfied: fsspec<=2024.6.1,>=2023.1.0 in c:\\anaconda\\lib\\site-packages (from fsspec[http]<=2024.6.1,>=2023.1.0->datasets) (2024.6.1)\n",
      "Requirement already satisfied: aiohttp in c:\\anaconda\\lib\\site-packages (from datasets) (3.10.3)\n",
      "Requirement already satisfied: huggingface-hub>=0.21.2 in c:\\anaconda\\lib\\site-packages (from datasets) (0.24.5)\n",
      "Requirement already satisfied: packaging in c:\\anaconda\\lib\\site-packages (from datasets) (24.1)\n",
      "Requirement already satisfied: pyyaml>=5.1 in c:\\anaconda\\lib\\site-packages (from datasets) (6.0.2)\n",
      "Requirement already satisfied: aiohappyeyeballs>=2.3.0 in c:\\anaconda\\lib\\site-packages (from aiohttp->datasets) (2.3.7)\n",
      "Requirement already satisfied: aiosignal>=1.1.2 in c:\\anaconda\\lib\\site-packages (from aiohttp->datasets) (1.3.1)\n",
      "Requirement already satisfied: attrs>=17.3.0 in c:\\anaconda\\lib\\site-packages (from aiohttp->datasets) (24.2.0)\n",
      "Requirement already satisfied: frozenlist>=1.1.1 in c:\\anaconda\\lib\\site-packages (from aiohttp->datasets) (1.4.1)\n",
      "Requirement already satisfied: multidict<7.0,>=4.5 in c:\\anaconda\\lib\\site-packages (from aiohttp->datasets) (6.0.5)\n",
      "Requirement already satisfied: yarl<2.0,>=1.0 in c:\\anaconda\\lib\\site-packages (from aiohttp->datasets) (1.9.4)\n",
      "Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\\anaconda\\lib\\site-packages (from huggingface-hub>=0.21.2->datasets) (4.12.2)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in c:\\anaconda\\lib\\site-packages (from requests>=2.32.2->datasets) (3.3.2)\n",
      "Requirement already satisfied: idna<4,>=2.5 in c:\\anaconda\\lib\\site-packages (from requests>=2.32.2->datasets) (3.7)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in c:\\anaconda\\lib\\site-packages (from requests>=2.32.2->datasets) (2.2.2)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in c:\\anaconda\\lib\\site-packages (from requests>=2.32.2->datasets) (2024.7.4)\n",
      "Requirement already satisfied: colorama in c:\\anaconda\\lib\\site-packages (from tqdm>=4.66.3->datasets) (0.4.6)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in c:\\anaconda\\lib\\site-packages (from pandas->datasets) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2020.1 in c:\\anaconda\\lib\\site-packages (from pandas->datasets) (2024.1)\n",
      "Requirement already satisfied: tzdata>=2022.7 in c:\\anaconda\\lib\\site-packages (from pandas->datasets) (2024.1)\n",
      "Requirement already satisfied: six>=1.5 in c:\\anaconda\\lib\\site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.16.0)\n",
      "Requirement already satisfied: ipywidgets in c:\\anaconda\\lib\\site-packages (8.1.3)\n",
      "Requirement already satisfied: comm>=0.1.3 in c:\\anaconda\\lib\\site-packages (from ipywidgets) (0.2.1)\n",
      "Requirement already satisfied: ipython>=6.1.0 in c:\\anaconda\\lib\\site-packages (from ipywidgets) (8.25.0)\n",
      "Requirement already satisfied: traitlets>=4.3.1 in c:\\anaconda\\lib\\site-packages (from ipywidgets) (5.14.3)\n",
      "Requirement already satisfied: widgetsnbextension~=4.0.11 in c:\\anaconda\\lib\\site-packages (from ipywidgets) (4.0.11)\n",
      "Requirement already satisfied: jupyterlab-widgets~=3.0.11 in c:\\anaconda\\lib\\site-packages (from ipywidgets) (3.0.11)\n",
      "Requirement already satisfied: decorator in c:\\anaconda\\lib\\site-packages (from ipython>=6.1.0->ipywidgets) (5.1.1)\n",
      "Requirement already satisfied: jedi>=0.16 in c:\\anaconda\\lib\\site-packages (from ipython>=6.1.0->ipywidgets) (0.18.1)\n",
      "Requirement already satisfied: matplotlib-inline in c:\\anaconda\\lib\\site-packages (from ipython>=6.1.0->ipywidgets) (0.1.6)\n",
      "Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in c:\\anaconda\\lib\\site-packages (from ipython>=6.1.0->ipywidgets) (3.0.43)\n",
      "Requirement already satisfied: pygments>=2.4.0 in c:\\anaconda\\lib\\site-packages (from ipython>=6.1.0->ipywidgets) (2.15.1)\n",
      "Requirement already satisfied: stack-data in c:\\anaconda\\lib\\site-packages (from ipython>=6.1.0->ipywidgets) (0.2.0)\n",
      "Requirement already satisfied: colorama in c:\\anaconda\\lib\\site-packages (from ipython>=6.1.0->ipywidgets) (0.4.6)\n",
      "Requirement already satisfied: parso<0.9.0,>=0.8.0 in c:\\anaconda\\lib\\site-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets) (0.8.3)\n",
      "Requirement already satisfied: wcwidth in c:\\anaconda\\lib\\site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets) (0.2.5)\n",
      "Requirement already satisfied: executing in c:\\anaconda\\lib\\site-packages (from stack-data->ipython>=6.1.0->ipywidgets) (0.8.3)\n",
      "Requirement already satisfied: asttokens in c:\\anaconda\\lib\\site-packages (from stack-data->ipython>=6.1.0->ipywidgets) (2.0.5)\n",
      "Requirement already satisfied: pure-eval in c:\\anaconda\\lib\\site-packages (from stack-data->ipython>=6.1.0->ipywidgets) (0.2.2)\n",
      "Requirement already satisfied: six in c:\\anaconda\\lib\\site-packages (from asttokens->stack-data->ipython>=6.1.0->ipywidgets) (1.16.0)\n",
      "Collecting pyarrow\n",
      "  Using cached pyarrow-17.0.0-cp312-cp312-win_amd64.whl.metadata (3.4 kB)\n",
      "Collecting numpy>=1.16.6 (from pyarrow)\n",
      "  Using cached numpy-2.0.1-cp312-cp312-win_amd64.whl.metadata (60 kB)\n",
      "Using cached pyarrow-17.0.0-cp312-cp312-win_amd64.whl (25.1 MB)\n",
      "Using cached numpy-2.0.1-cp312-cp312-win_amd64.whl (16.3 MB)\n",
      "Installing collected packages: numpy, pyarrow\n",
      "  Attempting uninstall: numpy\n",
      "    Found existing installation: numpy 1.26.4\n",
      "    Uninstalling numpy-1.26.4:\n",
      "      Successfully uninstalled numpy-1.26.4\n",
      "  Attempting uninstall: pyarrow\n",
      "    Found existing installation: pyarrow 17.0.0\n",
      "    Uninstalling pyarrow-17.0.0:\n",
      "      Successfully uninstalled pyarrow-17.0.0\n",
      "Successfully installed numpy-2.0.1 pyarrow-17.0.0\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n",
      "contourpy 1.2.0 requires numpy<2.0,>=1.20, but you have numpy 2.0.1 which is incompatible.\n",
      "numba 0.59.1 requires numpy<1.27,>=1.22, but you have numpy 2.0.1 which is incompatible.\n",
      "pywavelets 1.5.0 requires numpy<2.0,>=1.22.4, but you have numpy 2.0.1 which is incompatible.\n",
      "streamlit 1.32.0 requires numpy<2,>=1.19.3, but you have numpy 2.0.1 which is incompatible.\n",
      "streamlit 1.32.0 requires packaging<24,>=16.8, but you have packaging 24.1 which is incompatible.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting pyarrow\n",
      "  Using cached pyarrow-17.0.0-cp312-cp312-win_amd64.whl.metadata (3.4 kB)\n",
      "Collecting numpy>=1.16.6 (from pyarrow)\n",
      "  Using cached numpy-2.0.1-cp312-cp312-win_amd64.whl.metadata (60 kB)\n",
      "Using cached pyarrow-17.0.0-cp312-cp312-win_amd64.whl (25.1 MB)\n",
      "Using cached numpy-2.0.1-cp312-cp312-win_amd64.whl (16.3 MB)\n",
      "Installing collected packages: numpy, pyarrow\n",
      "  Attempting uninstall: numpy\n",
      "    Found existing installation: numpy 2.0.1\n",
      "    Uninstalling numpy-2.0.1:\n",
      "      Successfully uninstalled numpy-2.0.1\n",
      "  Attempting uninstall: pyarrow\n",
      "    Found existing installation: pyarrow 17.0.0\n",
      "    Uninstalling pyarrow-17.0.0:\n",
      "      Successfully uninstalled pyarrow-17.0.0\n",
      "Successfully installed numpy-2.0.1 pyarrow-17.0.0\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n",
      "contourpy 1.2.0 requires numpy<2.0,>=1.20, but you have numpy 2.0.1 which is incompatible.\n",
      "numba 0.59.1 requires numpy<1.27,>=1.22, but you have numpy 2.0.1 which is incompatible.\n",
      "pywavelets 1.5.0 requires numpy<2.0,>=1.22.4, but you have numpy 2.0.1 which is incompatible.\n",
      "streamlit 1.32.0 requires numpy<2,>=1.19.3, but you have numpy 2.0.1 which is incompatible.\n",
      "streamlit 1.32.0 requires packaging<24,>=16.8, but you have packaging 24.1 which is incompatible.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting datasets\n",
      "  Using cached datasets-2.21.0-py3-none-any.whl.metadata (21 kB)\n",
      "Collecting filelock (from datasets)\n",
      "  Using cached filelock-3.15.4-py3-none-any.whl.metadata (2.9 kB)\n",
      "Collecting numpy>=1.17 (from datasets)\n",
      "  Using cached numpy-2.0.1-cp312-cp312-win_amd64.whl.metadata (60 kB)\n",
      "Collecting pyarrow>=15.0.0 (from datasets)\n",
      "  Using cached pyarrow-17.0.0-cp312-cp312-win_amd64.whl.metadata (3.4 kB)\n",
      "Collecting dill<0.3.9,>=0.3.0 (from datasets)\n",
      "  Using cached dill-0.3.8-py3-none-any.whl.metadata (10 kB)\n",
      "Collecting pandas (from datasets)\n",
      "  Using cached pandas-2.2.2-cp312-cp312-win_amd64.whl.metadata (19 kB)\n",
      "Collecting requests>=2.32.2 (from datasets)\n",
      "  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)\n",
      "Collecting tqdm>=4.66.3 (from datasets)\n",
      "  Using cached tqdm-4.66.5-py3-none-any.whl.metadata (57 kB)\n",
      "Collecting xxhash (from datasets)\n",
      "  Using cached xxhash-3.5.0-cp312-cp312-win_amd64.whl.metadata (13 kB)\n",
      "Collecting multiprocess (from datasets)\n",
      "  Using cached multiprocess-0.70.16-py312-none-any.whl.metadata (7.2 kB)\n",
      "Collecting fsspec<=2024.6.1,>=2023.1.0 (from fsspec[http]<=2024.6.1,>=2023.1.0->datasets)\n",
      "  Using cached fsspec-2024.6.1-py3-none-any.whl.metadata (11 kB)\n",
      "Collecting aiohttp (from datasets)\n",
      "  Using cached aiohttp-3.10.3-cp312-cp312-win_amd64.whl.metadata (7.8 kB)\n",
      "Collecting huggingface-hub>=0.21.2 (from datasets)\n",
      "  Using cached huggingface_hub-0.24.5-py3-none-any.whl.metadata (13 kB)\n",
      "Collecting packaging (from datasets)\n",
      "  Using cached packaging-24.1-py3-none-any.whl.metadata (3.2 kB)\n",
      "Collecting pyyaml>=5.1 (from datasets)\n",
      "  Using cached PyYAML-6.0.2-cp312-cp312-win_amd64.whl.metadata (2.1 kB)\n",
      "Collecting aiohappyeyeballs>=2.3.0 (from aiohttp->datasets)\n",
      "  Using cached aiohappyeyeballs-2.3.7-py3-none-any.whl.metadata (5.9 kB)\n",
      "Collecting aiosignal>=1.1.2 (from aiohttp->datasets)\n",
      "  Using cached aiosignal-1.3.1-py3-none-any.whl.metadata (4.0 kB)\n",
      "Collecting attrs>=17.3.0 (from aiohttp->datasets)\n",
      "  Using cached attrs-24.2.0-py3-none-any.whl.metadata (11 kB)\n",
      "Collecting frozenlist>=1.1.1 (from aiohttp->datasets)\n",
      "  Using cached frozenlist-1.4.1-cp312-cp312-win_amd64.whl.metadata (12 kB)\n",
      "Collecting multidict<7.0,>=4.5 (from aiohttp->datasets)\n",
      "  Using cached multidict-6.0.5-cp312-cp312-win_amd64.whl.metadata (4.3 kB)\n",
      "Collecting yarl<2.0,>=1.0 (from aiohttp->datasets)\n",
      "  Using cached yarl-1.9.4-cp312-cp312-win_amd64.whl.metadata (32 kB)\n",
      "Collecting typing-extensions>=3.7.4.3 (from huggingface-hub>=0.21.2->datasets)\n",
      "  Using cached typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)\n",
      "Collecting charset-normalizer<4,>=2 (from requests>=2.32.2->datasets)\n",
      "  Using cached charset_normalizer-3.3.2-cp312-cp312-win_amd64.whl.metadata (34 kB)\n",
      "Collecting idna<4,>=2.5 (from requests>=2.32.2->datasets)\n",
      "  Using cached idna-3.7-py3-none-any.whl.metadata (9.9 kB)\n",
      "Collecting urllib3<3,>=1.21.1 (from requests>=2.32.2->datasets)\n",
      "  Using cached urllib3-2.2.2-py3-none-any.whl.metadata (6.4 kB)\n",
      "Collecting certifi>=2017.4.17 (from requests>=2.32.2->datasets)\n",
      "  Using cached certifi-2024.7.4-py3-none-any.whl.metadata (2.2 kB)\n",
      "Collecting colorama (from tqdm>=4.66.3->datasets)\n",
      "  Using cached colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)\n",
      "Collecting python-dateutil>=2.8.2 (from pandas->datasets)\n",
      "  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)\n",
      "Collecting pytz>=2020.1 (from pandas->datasets)\n",
      "  Using cached pytz-2024.1-py2.py3-none-any.whl.metadata (22 kB)\n",
      "Collecting tzdata>=2022.7 (from pandas->datasets)\n",
      "  Using cached tzdata-2024.1-py2.py3-none-any.whl.metadata (1.4 kB)\n",
      "Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas->datasets)\n",
      "  Using cached six-1.16.0-py2.py3-none-any.whl.metadata (1.8 kB)\n",
      "Using cached datasets-2.21.0-py3-none-any.whl (527 kB)\n",
      "Using cached dill-0.3.8-py3-none-any.whl (116 kB)\n",
      "Using cached fsspec-2024.6.1-py3-none-any.whl (177 kB)\n",
      "Using cached aiohttp-3.10.3-cp312-cp312-win_amd64.whl (377 kB)\n",
      "Using cached huggingface_hub-0.24.5-py3-none-any.whl (417 kB)\n",
      "Using cached numpy-2.0.1-cp312-cp312-win_amd64.whl (16.3 MB)\n",
      "Using cached packaging-24.1-py3-none-any.whl (53 kB)\n",
      "Using cached pyarrow-17.0.0-cp312-cp312-win_amd64.whl (25.1 MB)\n",
      "Using cached PyYAML-6.0.2-cp312-cp312-win_amd64.whl (156 kB)\n",
      "Using cached requests-2.32.3-py3-none-any.whl (64 kB)\n",
      "Using cached tqdm-4.66.5-py3-none-any.whl (78 kB)\n",
      "Using cached filelock-3.15.4-py3-none-any.whl (16 kB)\n",
      "Using cached multiprocess-0.70.16-py312-none-any.whl (146 kB)\n",
      "Using cached pandas-2.2.2-cp312-cp312-win_amd64.whl (11.5 MB)\n",
      "Using cached xxhash-3.5.0-cp312-cp312-win_amd64.whl (30 kB)\n",
      "Using cached aiohappyeyeballs-2.3.7-py3-none-any.whl (12 kB)\n",
      "Using cached aiosignal-1.3.1-py3-none-any.whl (7.6 kB)\n",
      "Using cached attrs-24.2.0-py3-none-any.whl (63 kB)\n",
      "Using cached certifi-2024.7.4-py3-none-any.whl (162 kB)\n",
      "Using cached charset_normalizer-3.3.2-cp312-cp312-win_amd64.whl (100 kB)\n",
      "Using cached frozenlist-1.4.1-cp312-cp312-win_amd64.whl (50 kB)\n",
      "Using cached idna-3.7-py3-none-any.whl (66 kB)\n",
      "Using cached multidict-6.0.5-cp312-cp312-win_amd64.whl (27 kB)\n",
      "Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)\n",
      "Using cached pytz-2024.1-py2.py3-none-any.whl (505 kB)\n",
      "Using cached typing_extensions-4.12.2-py3-none-any.whl (37 kB)\n",
      "Using cached tzdata-2024.1-py2.py3-none-any.whl (345 kB)\n",
      "Using cached urllib3-2.2.2-py3-none-any.whl (121 kB)\n",
      "Using cached yarl-1.9.4-cp312-cp312-win_amd64.whl (76 kB)\n",
      "Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)\n",
      "Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)\n",
      "Installing collected packages: pytz, xxhash, urllib3, tzdata, typing-extensions, six, pyyaml, packaging, numpy, multidict, idna, fsspec, frozenlist, filelock, dill, colorama, charset-normalizer, certifi, attrs, aiohappyeyeballs, yarl, tqdm, requests, python-dateutil, pyarrow, multiprocess, aiosignal, pandas, huggingface-hub, aiohttp, datasets\n",
      "  Attempting uninstall: pytz\n",
      "    Found existing installation: pytz 2024.1\n",
      "    Uninstalling pytz-2024.1:\n",
      "      Successfully uninstalled pytz-2024.1\n",
      "  Attempting uninstall: xxhash\n",
      "    Found existing installation: xxhash 3.5.0\n",
      "    Uninstalling xxhash-3.5.0:\n",
      "      Successfully uninstalled xxhash-3.5.0\n",
      "  Attempting uninstall: urllib3\n",
      "    Found existing installation: urllib3 2.2.2\n",
      "    Uninstalling urllib3-2.2.2:\n",
      "      Successfully uninstalled urllib3-2.2.2\n",
      "  Attempting uninstall: tzdata\n",
      "    Found existing installation: tzdata 2024.1\n",
      "    Uninstalling tzdata-2024.1:\n",
      "      Successfully uninstalled tzdata-2024.1\n",
      "  Attempting uninstall: typing-extensions\n",
      "    Found existing installation: typing_extensions 4.12.2\n",
      "    Uninstalling typing_extensions-4.12.2:\n",
      "      Successfully uninstalled typing_extensions-4.12.2\n",
      "  Attempting uninstall: six\n",
      "    Found existing installation: six 1.16.0\n",
      "    Uninstalling six-1.16.0:\n",
      "      Successfully uninstalled six-1.16.0\n",
      "  Attempting uninstall: pyyaml\n",
      "    Found existing installation: PyYAML 6.0.2\n",
      "    Uninstalling PyYAML-6.0.2:\n",
      "      Successfully uninstalled PyYAML-6.0.2\n",
      "  Attempting uninstall: packaging\n",
      "    Found existing installation: packaging 24.1\n",
      "    Uninstalling packaging-24.1:\n",
      "      Successfully uninstalled packaging-24.1\n",
      "  Attempting uninstall: numpy\n",
      "    Found existing installation: numpy 2.0.1\n",
      "    Uninstalling numpy-2.0.1:\n",
      "      Successfully uninstalled numpy-2.0.1\n",
      "  Attempting uninstall: multidict\n",
      "    Found existing installation: multidict 6.0.5\n",
      "    Uninstalling multidict-6.0.5:\n",
      "      Successfully uninstalled multidict-6.0.5\n",
      "  Attempting uninstall: idna\n",
      "    Found existing installation: idna 3.7\n",
      "    Uninstalling idna-3.7:\n",
      "      Successfully uninstalled idna-3.7\n",
      "  Attempting uninstall: fsspec\n",
      "    Found existing installation: fsspec 2024.6.1\n",
      "    Uninstalling fsspec-2024.6.1:\n",
      "      Successfully uninstalled fsspec-2024.6.1\n",
      "  Attempting uninstall: frozenlist\n",
      "    Found existing installation: frozenlist 1.4.1\n",
      "    Uninstalling frozenlist-1.4.1:\n",
      "      Successfully uninstalled frozenlist-1.4.1\n",
      "  Attempting uninstall: filelock\n",
      "    Found existing installation: filelock 3.15.4\n",
      "    Uninstalling filelock-3.15.4:\n",
      "      Successfully uninstalled filelock-3.15.4\n",
      "  Attempting uninstall: dill\n",
      "    Found existing installation: dill 0.3.8\n",
      "    Uninstalling dill-0.3.8:\n",
      "      Successfully uninstalled dill-0.3.8\n",
      "  Attempting uninstall: colorama\n",
      "    Found existing installation: colorama 0.4.6\n",
      "    Uninstalling colorama-0.4.6:\n",
      "      Successfully uninstalled colorama-0.4.6\n",
      "  Attempting uninstall: charset-normalizer\n",
      "    Found existing installation: charset-normalizer 3.3.2\n",
      "    Uninstalling charset-normalizer-3.3.2:\n",
      "      Successfully uninstalled charset-normalizer-3.3.2\n",
      "  Attempting uninstall: certifi\n",
      "    Found existing installation: certifi 2024.7.4\n",
      "    Uninstalling certifi-2024.7.4:\n",
      "      Successfully uninstalled certifi-2024.7.4\n",
      "  Attempting uninstall: attrs\n",
      "    Found existing installation: attrs 24.2.0\n",
      "    Uninstalling attrs-24.2.0:\n",
      "      Successfully uninstalled attrs-24.2.0\n",
      "  Attempting uninstall: aiohappyeyeballs\n",
      "    Found existing installation: aiohappyeyeballs 2.3.7\n",
      "    Uninstalling aiohappyeyeballs-2.3.7:\n",
      "      Successfully uninstalled aiohappyeyeballs-2.3.7\n",
      "  Attempting uninstall: yarl\n",
      "    Found existing installation: yarl 1.9.4\n",
      "    Uninstalling yarl-1.9.4:\n",
      "      Successfully uninstalled yarl-1.9.4\n",
      "  Attempting uninstall: tqdm\n",
      "    Found existing installation: tqdm 4.66.5\n",
      "    Uninstalling tqdm-4.66.5:\n",
      "      Successfully uninstalled tqdm-4.66.5\n",
      "  Attempting uninstall: requests\n",
      "    Found existing installation: requests 2.32.3\n",
      "    Uninstalling requests-2.32.3:\n",
      "      Successfully uninstalled requests-2.32.3\n",
      "  Attempting uninstall: python-dateutil\n",
      "    Found existing installation: python-dateutil 2.9.0.post0\n",
      "    Uninstalling python-dateutil-2.9.0.post0:\n",
      "      Successfully uninstalled python-dateutil-2.9.0.post0\n",
      "  Attempting uninstall: pyarrow\n",
      "    Found existing installation: pyarrow 17.0.0\n",
      "    Uninstalling pyarrow-17.0.0:\n",
      "      Successfully uninstalled pyarrow-17.0.0\n",
      "  Attempting uninstall: multiprocess\n",
      "    Found existing installation: multiprocess 0.70.16\n",
      "    Uninstalling multiprocess-0.70.16:\n",
      "      Successfully uninstalled multiprocess-0.70.16\n",
      "  Attempting uninstall: aiosignal\n",
      "    Found existing installation: aiosignal 1.3.1\n",
      "    Uninstalling aiosignal-1.3.1:\n",
      "      Successfully uninstalled aiosignal-1.3.1\n",
      "  Attempting uninstall: pandas\n",
      "    Found existing installation: pandas 2.2.2\n",
      "    Uninstalling pandas-2.2.2:\n",
      "      Successfully uninstalled pandas-2.2.2\n",
      "  Attempting uninstall: huggingface-hub\n",
      "    Found existing installation: huggingface-hub 0.24.5\n",
      "    Uninstalling huggingface-hub-0.24.5:\n",
      "      Successfully uninstalled huggingface-hub-0.24.5\n",
      "  Attempting uninstall: aiohttp\n",
      "    Found existing installation: aiohttp 3.10.3\n",
      "    Uninstalling aiohttp-3.10.3:\n",
      "      Successfully uninstalled aiohttp-3.10.3\n",
      "  Attempting uninstall: datasets\n",
      "    Found existing installation: datasets 2.21.0\n",
      "    Uninstalling datasets-2.21.0:\n",
      "      Successfully uninstalled datasets-2.21.0\n",
      "Successfully installed aiohappyeyeballs-2.3.7 aiohttp-3.10.3 aiosignal-1.3.1 attrs-24.2.0 certifi-2024.7.4 charset-normalizer-3.3.2 colorama-0.4.6 datasets-2.21.0 dill-0.3.8 filelock-3.15.4 frozenlist-1.4.1 fsspec-2024.6.1 huggingface-hub-0.24.5 idna-3.7 multidict-6.0.5 multiprocess-0.70.16 numpy-2.0.1 packaging-24.1 pandas-2.2.2 pyarrow-17.0.0 python-dateutil-2.9.0.post0 pytz-2024.1 pyyaml-6.0.2 requests-2.32.3 six-1.16.0 tqdm-4.66.5 typing-extensions-4.12.2 tzdata-2024.1 urllib3-2.2.2 xxhash-3.5.0 yarl-1.9.4\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n",
      "contourpy 1.2.0 requires numpy<2.0,>=1.20, but you have numpy 2.0.1 which is incompatible.\n",
      "numba 0.59.1 requires numpy<1.27,>=1.22, but you have numpy 2.0.1 which is incompatible.\n",
      "pywavelets 1.5.0 requires numpy<2.0,>=1.22.4, but you have numpy 2.0.1 which is incompatible.\n",
      "s3fs 2024.3.1 requires fsspec==2024.3.1, but you have fsspec 2024.6.1 which is incompatible.\n",
      "streamlit 1.32.0 requires numpy<2,>=1.19.3, but you have numpy 2.0.1 which is incompatible.\n",
      "streamlit 1.32.0 requires packaging<24,>=16.8, but you have packaging 24.1 which is incompatible.\n"
     ]
    }
   ],
   "source": [
    "!pip install numpy\n",
    "!pip install scikit-learn\n",
    "!pip install pandas\n",
    "!pip install torch\n",
    "!pip install matplotlib\n",
    "!pip install scikit-learn gensim transformers sentence-transformers\n",
    "!pip install transformers torch scikit-learn\n",
    "!pip install datasets\n",
    "!pip install ipywidgets \n",
    "!pip install --upgrade --force-reinstall pyarrow\n",
    "!pip install --upgrade --force-reinstall pyarrow\n",
    "!pip install --upgrade --force-reinstall datasets\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 103,
   "id": "9e3c624b-6cc7-4769-9683-950a9b4ba356",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.\n",
      "A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.\n",
      "A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.\n",
      "A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.\n",
      "A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.\n",
      "A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.\n",
      "A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.\n",
      "A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.\n",
      "A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.\n",
      "A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.\n",
      "A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.\n",
      "A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.\n",
      "A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.\n",
      "A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.\n",
      "A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.\n",
      "A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.\n",
      "A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.\n",
      "A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.\n",
      "A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.\n",
      "A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.\n",
      "A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.\n",
      "A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.\n",
      "A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.\n",
      "A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.\n",
      "A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.\n",
      "A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.\n",
      "A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.\n",
      "A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.\n",
      "A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.\n",
      "A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.\n",
      "A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.\n",
      "A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.\n",
      "A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.\n",
      "A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.\n",
      "A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.\n",
      "A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.\n",
      "A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.\n",
      "A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.\n",
      "A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.\n",
      "A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.\n",
      "A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.\n",
      "A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.\n",
      "A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.\n",
      "A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.\n",
      "A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.\n",
      "A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.\n",
      "A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.\n",
      "A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.\n",
      "A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.\n",
      "A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.\n",
      "A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.\n",
      "A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.\n",
      "C:\\anaconda\\Lib\\site-packages\\transformers\\tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Combined claims length: 865 words\n",
      "Combined claims length: 471 words\n",
      "Combined claims length: 203 words\n",
      "Combined claims length: 617 words\n",
      "Combined claims length: 33 words\n",
      "Group 0 Title: System comprisesa processor anda memory store executable instruction executed processor. processor facilitate performance operation\n",
      "Group 1 Title: The gcp message protocol gcp. method according toclaim comprises routing said\n",
      "Group 2 Title:  system ofclaim wherein microphone comprises microelectromechanical system mem microphone system of\n",
      "Group 3 Title: Method medium gateway connection backbone comprising step measuring packet loss jitter associated said backbone receiving call\n",
      "Group 4 Title:  processor measuring output voltage importing output data time domain waveform representing output signal processor obtaining output\n",
      "Group 0:\n",
      "  - system comprisinga processor anda memory store executable instruction executed processor facilitate performance operation comprisingobtaining pressurein signalout transfer function representing distortion output signal microphone corresponding input stimulus defined sound pressure level spl applied microphonecreating ideal sine wave stimulus based amplitude time domain waveform representing output signal fundamental frequency time domain waveformgenerating based defined relationship ideal sine wave stimulus time domain waveform equation representing pressurein signalout transfer function representing distortion output signal andinverting equation obtain inverse transfer function facilitating application microphone inverse transfer function output signal obtain linearized output representing input stimulus\n",
      "  - memory store executable instruction executed processor facilitate performance operation comprisingobtaining pressurein signalout transfer function representing distortion output signal microphone corresponding input stimulus defined sound pressure level spl applied microphonecreating ideal sine wave stimulus based amplitude time domain waveform representing output signal fundamental frequency time domain waveformgenerating based defined relationship ideal sine wave stimulus time domain waveform equation representing pressurein signalout transfer function representing distortion output signal andinverting equation obtain inverse transfer function facilitating application microphone inverse transfer function output signal obtain linearized output representing input stimulus\n",
      "  - obtaining pressurein signalout transfer function representing distortion output signal microphone corresponding input stimulus defined sound pressure level spl applied microphone\n",
      "  - creating ideal sine wave stimulus based amplitude time domain waveform representing output signal fundamental frequency time domain waveform\n",
      "  - generating based defined relationship ideal sine wave stimulus time domain waveform equation representing pressurein signalout transfer function representing distortion output signal\n",
      "  - inverting equation obtain inverse transfer function facilitating application microphone inverse transfer function output signal obtain linearized output representing input stimulus\n",
      "  - system ofclaim wherein obtaining comprisesderiving simulation defined model microphone comprising production based parameter microphone output signal\n",
      "  - deriving simulation defined model microphone comprising production based parameter microphone output signal\n",
      "  - system ofclaim wherein obtaining comprisesimporting output data time domain waveform representing output signal andbased output data obtaining property time domain waveform comprising amplitude time domain waveform fundamental frequency time domain waveform\n",
      "  - system ofclaim wherein defined relationship represents voltage difference ideal sine wave stimulus time domain waveform respect defined alignment respective phase ideal sine wave stimulus time domain waveform\n",
      "  - microelectromechanical system mem microphone comprisinga processor anda memory store executable instruction executed processor facilitate performance operation comprisingcreating ideal sine wave stimulus representing output signal mem microphone respect input stimulus defined sound pressure level spl applied mem microphone wherein ideal sine wave stimulus based amplitude time domain waveform representing output signal fundamental frequency time domain waveformderiving based defined relationship ideal sine wave stimulus time domain waveform equation transfer function representing distortion output signal andapplying based equation linearization filter output signal obtain linearized output representing input stimulus\n",
      "  - memory store executable instruction executed processor facilitate performance operation comprisingcreating ideal sine wave stimulus representing output signal mem microphone respect input stimulus defined sound pressure level spl applied mem microphone wherein ideal sine wave stimulus based amplitude time domain waveform representing output signal fundamental frequency time domain waveformderiving based defined relationship ideal sine wave stimulus time domain waveform equation transfer function representing distortion output signal andapplying based equation linearization filter output signal obtain linearized output representing input stimulus\n",
      "  - creating ideal sine wave stimulus representing output signal mem microphone respect input stimulus defined sound pressure level spl applied mem microphone wherein ideal sine wave stimulus based amplitude time domain waveform representing output signal fundamental frequency time domain waveform\n",
      "  - deriving based defined relationship ideal sine wave stimulus time domain waveform equation transfer function representing distortion output signal\n",
      "  - mem microphone ofclaim wherein output signal output voltage wherein deriving equation comprisesobtaining output data time domain waveform representing output voltage andbased output data deriving property time domain waveform comprising amplitude time domain waveform fundamental frequency time domain waveform\n",
      "  - mem microphone ofclaim wherein defined relationship represents voltage difference ideal sine wave stimulus time domain waveform respect defined alignment respective phase ideal sine wave stimulus time domain waveform\n",
      "  - method comprisinggenerating system comprising processor sine wave stimulus representing output signal microphone respect input stimulus applied microphone wherein sine wave stimulus based amplitude time domain waveform representing output signal fundamental frequency time domain waveformselecting system based defined relationship sine wave stimulus time domain waveform equation transfer function representing distortion output signal andfacilitating system application microphone inversion equation output signal obtain linearized output representing input stimulus\n",
      "  - generating system comprising processor sine wave stimulus representing output signal microphone respect input stimulus applied microphone wherein sine wave stimulus based amplitude time domain waveform representing output signal fundamental frequency time domain waveform\n",
      "  - selecting system based defined relationship sine wave stimulus time domain waveform equation transfer function representing distortion output signal\n",
      "  - method ofclaim wherein generating sine wave stimulus comprisesobtaining data representing output signal microphone andgenerating sine wave stimulus amplitude time domain waveform fundamental frequency time domain waveform\n",
      "  - generating sine wave stimulus amplitude time domain waveform fundamental frequency time domain waveform\n",
      "  - method ofclaim wherein output signal voltage output wherein selecting comprisesderiving simulation defined model microphone based defined production parameter corresponding microphone voltage output\n",
      "  - deriving simulation defined model microphone based defined production parameter corresponding microphone voltage output\n",
      "  - method ofclaim wherein selecting comprisesselecting equation based voltage difference sine wave stimulus time domain waveform respect defined alignment respective phase sine wave stimulus time domain waveform\n",
      "  - selecting equation based voltage difference sine wave stimulus time domain waveform respect defined alignment respective phase sine wave stimulus time domain waveform\n",
      "Group 1:\n",
      "  - method according toclaim wherein said indication received external source mobile switching centre server\n",
      "  - method according toclaim wherein said indication received gateway control protocol gcp message\n",
      "  - method according toclaim wherein said indication priority value within gcp message\n",
      "  - method according toclaim wherein said gcp message context request\n",
      "  - method according toclaim wherein said indication received internal source\n",
      "  - method according toclaim comprising routing said call second backbone connected said medium gateway\n",
      "  - method according toclaim wherein said internal source calendar\n",
      "  - medium gateway according toclaim wherein said mean connecting said backbone configured receive said indication external source mobile switching centre server\n",
      "  - medium gateway according toclaim comprising internal source providing said indication\n",
      "  - medium gateway according toclaim wherein said mean deciding configured route said call second backbone connected said medium gateway\n",
      "  - system ofclaim wherein output signal output voltage wherein obtaining comprisesmeasuring output voltage\n",
      "  - based output data obtaining property time domain waveform comprising amplitude time domain waveform fundamental frequency time domain waveform\n",
      "  - system ofclaim wherein distortion comprises oddorder harmonic distortion evenorder harmonic distortion\n",
      "  - system ofclaim wherein distortion frequency dependent wherein distortion time dependent\n",
      "  - applying based equation linearization filter output signal obtain linearized output representing input stimulus\n",
      "  - based output data deriving property time domain waveform comprising amplitude time domain waveform fundamental frequency time domain waveform\n",
      "  - facilitating system application microphone inversion equation output signal obtain linearized output representing input stimulus\n",
      "  - method ofclaim wherein output signal voltage output wherein selecting comprisesmeasuring system voltage output\n",
      "  - claim wireless telephone apparatus comprising handset onioffhook switch wireless communication module establishing first second cellular telephone call via base station mean generating explicit call transfer command sending base station response activation onhook switch first second wireless call established apparatus\n",
      "  - apparatus claim ftirther comprising call receiving mean receiving first call calling party call initiating mean entering call initiation mode response activation first predetermined button initiating second call transfer mean putting first call hold initiating second call toggling response activation first predetermined button first second call\n",
      "  - apparatus claim wherein first predetermined button redial button\n",
      "  - apparatus claim wherein transfer mean toggle first second call putting either first second call hold\n",
      "  - apparatus one claim comprising mean enabling phonebook lookup operation call initiation mode\n",
      "  - apparatus one claim wherein call initiation mode dialling mode entered using first predetermined button\n",
      "  - apparatus one preceding claim comprising display mean displaying first second icon adjacent information relating first second call respectively first second icon adapted switch toggling call\n",
      "  - apparatus claim comprising selection mean selecting information displayed display mean\n",
      "  - apparatus claim wherein transfer mean adapted initiate call second party whose information displayed display mean\n",
      "  - apparatus one claim comprising second predetermined button end active call reverts call hold\n",
      "  - apparatus claim wherein second predetermined button clear button\n",
      "  - method effecting call transfer comprising establishing first second cellular telephone call wireless telephone apparatus generating explicit call transfer command sending base station response activation onhook switch\n",
      "  - communication apparatus substantially herein described reference accompanying drawing figure\n",
      "Group 2:\n",
      "  - system ofclaim wherein microphone comprises microelectromechanical system mem microphone\n",
      "  - system ofclaim wherein mem microphone comprisesa diaphragm convert spl electrical signala single backplate capacitively coupled side diaphragm andan electronic amplifier buffer electrical signal generate output signal\n",
      "  - diaphragm convert spl electrical signal\n",
      "  - single backplate capacitively coupled side diaphragm\n",
      "  - electronic amplifier buffer electrical signal generate output signal\n",
      "  - system ofclaim wherein mem microphone comprisesa diaphragm convert spl electrical signaldual backplate capacitively coupled respective side diaphragm andan electronic amplifier buffer electrical signal generate output signal\n",
      "  - diaphragm convert spl electrical signal\n",
      "  - dual backplate capacitively coupled respective side diaphragm\n",
      "  - electronic amplifier buffer electrical signal generate output signal\n",
      "  - mem microphone ofclaim comprisinga diaphragm convert spl electrical signala single backplate capacitively coupled side diaphragm andan electronic amplifier buffer electrical signal generate output signal\n",
      "  - diaphragm convert spl electrical signal\n",
      "  - single backplate capacitively coupled side diaphragm\n",
      "  - electronic amplifier buffer electrical signal generate output signal\n",
      "  - mem microphone ofclaim comprisinga diaphragm convert spl electrical signaldual backplate capacitively coupled respective side diaphragm andan electronic amplifier buffer electrical signal generate output signal\n",
      "  - diaphragm convert spl electrical signal\n",
      "  - dual backplate capacitively coupled respective side diaphragm\n",
      "  - electronic amplifier buffer electrical signal generate output signal\n",
      "  - apparatus claim ftirther comprising body cradle handset wherein onloff hook switch operates response placing handset cradle\n",
      "Group 3:\n",
      "  - method medium gateway connection backbone comprising step measuring packet loss jitter associated said backbone receiving call measured packet loss exceeds predefined packet loss threshold measured jitter exceeds predefined jitter threshold said backbone detecting indication associated call wherein indication based time period associated predefined packet loss threshold predefined jitter threshold wherein indication indicates measured packet loss exceeding predefined packet loss threshold measured jitter exceeding predefined jitter threshold acceptable call said time period based least partially measured packet loss measured jitter said indication associated call deciding whether said call admitted routed via said backbone adjusting quality service qos level said call deciding said call admitted via said backbone\n",
      "  - method mobile switching centre server connection backbone comprising step receiving call setup request associated said backbone detecting call setup performed medium gateway even measured packet loss predefined packet loss threshold measured jitter predefined jitter threshold said backbone providing indication associated call said medium gateway wherein indication based time period associated predefined packet loss threshold predefined jitter threshold wherein indication indicates packet loss measurement predefined packet loss threshold jitter measurement predefined jitter threshold acceptable said time period indicating admit call via said backbone lower quality service accordingly wherein said indication received gateway control protocol gcp message\n",
      "  - method according toclaim wherein said step detecting comprises measuring call gradient analyzing call setup event overtime detecting call setup performed even measured packet loss predefined packet loss threshold andor measured jitter predefined jitter threshold said gradient predefined value\n",
      "  - method according toclaim wherein said step detecting comprises receiving indication measured packet loss predefined packet loss threshold measured jitter predefined jitter threshold originator said call acceptable\n",
      "  - method according toclaim wherein said step detecting comprises receiving indication measured packet loss predefined packet loss threshold measured jitter predefined jitter threshold destination said call acceptable\n",
      "  - medium gateway comprising mean connecting backbone said mean connecting configured receive call processing mean configured measure packet loss jitter said backbone said processing mean configured detect indication associated call wherein indication based time period associated predefined packet loss threshold predefined jitter threshold wherein indication indicates measured packet loss predefined packet loss threshold measured jitter predefined jitter threshold acceptable said time period said processing mean configured decide based least partially measured packet loss measured jitter said detected indication whether said call admitted routed via said backbone even measured packet loss exceeds predefined packet loss threshold measured jitter exceeds predefined jitter threshold said processing mean configured adjust quality service qos level said call deciding said call admitted routed via said backbone wherein said indication received gateway control protocol gcp message\n",
      "  - mobile switching centre server comprising mean connecting backbone said mean connecting configured receive call setup request associated said backbone mean processing configured detect call setup performed medium gateway even measured packet loss predefined packet loss threshold measured jitter predefined jitter threshold said backbone mean providing indication associated call medium gateway wherein indication based time period associated predefined packet loss threshold predefined jitter threshold wherein indication indicates measured packet loss predefined packet loss threshold measured jitter predefined jitter threshold acceptable said time period indicating admit call via said backbone lower quality service accordingly\n",
      "  - mobile switching centre server according toclaim wherein said mean processing configured measure call gradient analyzing call setup event time said mean processing configured detect call setup performed even measured packet loss predefined packet loss threshold measured jitter predefined jitter threshold said gradient predefined value\n",
      "  - mobile switching centre server according toclaim wherein said mean processing configured receive indication associated call indicating packet loss predefined packet loss threshold jitter predefined jitter threshold originator said call acceptable\n",
      "  - mobile switching centre server according toclaim wherein said mean processing configured receive indication associated call indicating measured packet loss predefined packet loss threshold measured jitter predefined jitter threshold destination said call acceptable\n",
      "Group 4:\n",
      "  - processor\n",
      "  - measuring output voltage\n",
      "  - importing output data time domain waveform representing output signal\n",
      "  - processor\n",
      "  - obtaining output data time domain waveform representing output voltage\n",
      "  - obtaining data representing output signal microphone\n",
      "  - measuring system voltage output\n"
     ]
    }
   ],
   "source": [
    "import torch\n",
    "import numpy as np\n",
    "import requests\n",
    "from bs4 import BeautifulSoup\n",
    "import re\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "from nltk.tokenize import word_tokenize\n",
    "from nltk.corpus import stopwords\n",
    "from nltk.stem import WordNetLemmatizer\n",
    "from transformers import BertTokenizer, BertModel\n",
    "from sklearn.cluster import AgglomerativeClustering\n",
    "from transformers import pipeline\n",
    "import os\n",
    "\n",
    "# Function to extract patent claims from URL\n",
    "def extract_patent_claims(url):\n",
    "    pages = requests.get(url)\n",
    "    soup = BeautifulSoup(pages.text, 'html.parser')\n",
    "    claims = soup.find_all('div', class_='claim-text')\n",
    "    extracted_claims = []\n",
    "    for claim in claims:\n",
    "        text = claim.get_text(strip=True)\n",
    "        extracted_claims.append(text)\n",
    "    return extracted_claims\n",
    "\n",
    "list_url = [\n",
    "    'https://patents.google.com/patent/US9634864B2/en?oq=US9634864B2',\n",
    "    'https://patents.google.com/patent/US9980046B2/en?oq=US9980046B2',\n",
    "    'https://patents.google.com/patent/GB2478972A/en?q=(phone)&oq=phone']\n",
    "\n",
    "claims = []\n",
    "for url in list_url:\n",
    "    claims.extend(extract_patent_claims(url))\n",
    "\n",
    "lemmatizer = WordNetLemmatizer()\n",
    "\n",
    "# Function to preprocess claims\n",
    "def preprocess_claims(claims):\n",
    "    stop_words = set(stopwords.words('english'))\n",
    "    processed_claims = []\n",
    "    \n",
    "    for claim in claims:\n",
    "        claim = claim.lower()\n",
    "        claim = re.sub(r'[^a-z\\s]', '', claim)\n",
    "        tokens = word_tokenize(claim)\n",
    "        tokens = [lemmatizer.lemmatize(word) for word in tokens if word not in stop_words]\n",
    "        processed_claims.append(' '.join(tokens))\n",
    "    \n",
    "    return processed_claims\n",
    "preprocessed_claims = preprocess_claims(claims)\n",
    "\n",
    "#BERT MODEL\n",
    "# Initialize the BERT tokenizer and model\n",
    "tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')\n",
    "model = BertModel.from_pretrained('bert-base-uncased')\n",
    "\n",
    "# Function to get BERT embeddings\n",
    "def get_bert_embeddings(texts):\n",
    "    embeddings = []\n",
    "    for text in texts:\n",
    "        inputs = tokenizer(text, return_tensors='pt', truncation=True, padding=True, max_length=512)\n",
    "        with torch.no_grad():\n",
    "            outputs = model(**inputs)\n",
    "            embeddings.append(outputs.last_hidden_state[:, 0, :].squeeze().numpy())\n",
    "    return np.array(embeddings)\n",
    "\n",
    "# Get BERT embeddings for the preprocessed claims\n",
    "embeddings = get_bert_embeddings(preprocessed_claims)\n",
    "\n",
    "# Perform clustering using Agglomerative Clustering with the updated parameter name\n",
    "cluster = AgglomerativeClustering(n_clusters=5, metric='euclidean', linkage='ward')\n",
    "cluster_labels = cluster.fit_predict(embeddings)\n",
    "\n",
    "# Group the claims by their assigned cluster\n",
    "grouped_claims = {i: [] for i in range(5)}\n",
    "for idx, label in enumerate(cluster_labels):\n",
    "    grouped_claims[label].append(preprocessed_claims[idx])\n",
    "\n",
    "# Initialize the summarization pipeline with a specific model\n",
    "summarizer = pipeline('summarization', model=\"facebook/bart-large-cnn\")\n",
    "\n",
    "# Function to generate a topic title for each group\n",
    "def generate_topic_title(claims):\n",
    "    combined_claims = ' '.join(claims)\n",
    "    words = combined_claims.split()\n",
    "    print(f\"Combined claims length: {len(words)} words\")\n",
    "    \n",
    "    # Summarize in chunks if too long\n",
    "    if len(words) > 512:\n",
    "        chunk_size = 256\n",
    "        summaries = []\n",
    "        for i in range(0, len(words), chunk_size):\n",
    "            chunk = ' '.join(words[i:i+chunk_size])\n",
    "            summary = summarizer(chunk, max_length=20, min_length=5, do_sample=False)\n",
    "            summaries.append(summary[0]['summary_text'])\n",
    "        \n",
    "        # Combine summaries and summarize again\n",
    "        combined_summary = ' '.join(summaries)\n",
    "        final_summary = summarizer(combined_summary, max_length=20, min_length=5, do_sample=False)\n",
    "        return final_summary[0]['summary_text']\n",
    "    else:\n",
    "        summary = summarizer(combined_claims, max_length=20, min_length=5, do_sample=False)\n",
    "        return summary[0]['summary_text']\n",
    "#Generating titles for each group makes it easier to understand, communicate, and work with the grouped data.\n",
    "group_titles = {group: generate_topic_title(claims) for group, claims in grouped_claims.items()}\n",
    "# Display group titles\n",
    "for group, title in group_titles.items():\n",
    "    print(f\"Group {group} Title: {title}\")\n",
    "\n",
    "# Display grouped claims \n",
    "for group, claims in grouped_claims.items():\n",
    "    print(f\"Group {group}:\")\n",
    "    for claim in claims:\n",
    "        print(f\"  - {claim}\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
